name: Behave Python Demo
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v3
    - name: Setup Python
      uses: python/setup-python@v4
      with:
        python-version: 3.10.8

    - name: Firefox Install
      uses: browser-action/setup-chrome@latest
      with:
        firefox-version: stable

    - name: Pip Install
      run: pip install -r requirements.txt

    - name: Behave Test
      run: behave